### ISSUE TITLE
Site Doesn't Work

### ISSUE THREAD

**Issue by aleksanderxh** [vicr123/vicr123.github.io#1]
When I try to visit vicr123.github.io it redirects me to vicr123.com which doesn't exist...
What is happening?

**Comment by vicr123** [comment]
My apologies, still trying to figure this out with my domain registrar. Hopefully it'll be back up soon. :P

**Comment by aleksanderxh** [comment]
Works Now!

**Comment by vicr123** [comment]
Should be fixed now :)

**Comment by aleksanderxh** [comment]
Works perfectly :)

Congrats on the new custom domain!
