### ISSUE TITLE
ONO

### ISSUE THREAD

**Issue by ghost** [vicr123/vicr123.github.io#6]
it says on http://vicr123.com/vtChSs.html Are you lost?  then says 
You seem to be lost...

And help is right here!

    Did you make a typo up there?
    Did the page you wanted to see exist before?
    Did I make a mistake? Probably. Thanks for telling me.

And if all else fails...

Here are some links you might like to try to get you back on track:
Home Page
the shell Home Page
Contemporary Home Page
theShell Help

Still lost? No? Good. What are you still doing here?

**Comment by ghost** [comment]
I don't know what to do please help!

**Comment by colorfulchair** [comment]
How did you get to that link? Where were you before you got that error?
It's hard to help with that little information.

**Comment by ghost** [comment]
on youtube

**Comment by colorfulchair** [comment]
You got to that page directly from a video? Could you please link the video?

**Comment by ghost** [comment]
The video is https://www.youtube.com/watch?v=2E21oad5pWQ&t

**Comment by colorfulchair** [comment]
You tried to access the Victor Tran Challenge spreadsheet, but that challenge doesn't exist anymore.

**Comment by ItsJamie9494** [comment]
It exists in other branches if you want to look for it. However, the challenge is closed.

**Comment by vicr123** [comment]
Closing this bug because the link is invalid, feel free to reopen if you've still got problems
